### ISSUE TITLE
Add OpenLCB CAN monitor to JMRI Actions

### ISSUE THREAD

**Issue by balazsracz** [openlcb/OpenLCB_Java#36]
@KenC57 reports the following:

It was the ‘Open CAN Monitor’ action in the startup. That’s the only entry I’m finding, not a ‘Open OpenLCB Monitor’ entry. If I do the OpenLCB->Traffic Monitor, then I see the full breakout of details.

So it seems the ‘good’ monitor isn’t being entered as an ‘Action’ item in JMRI.

**Comment by KenC57** [comment]
I'm thinking this should have been an item in the JMRI tracker.

 

Problem is figuring out where the actions list in preferences is being built
and change that. I used to know but trying to remember it right.

 

-ken c

**Comment by pabender** [comment]
On 11/06/2016 01:34 PM, Ken Cameron wrote:
> I'm thinking this should have been an item in the JMRI tracker.

I tend to agree.

> Problem is figuring out where the actions list in preferences is being 
> built
> and change that. I used to know but trying to remember it right.

I know the list of actions (for OpenLCB) is in 
jmri.jmrix.openlcb.OlcbActionListBundle.properties (and the translations 
of that).... the problem is I can't figure out where that gets added to 
the list of actions.  (supposedly it's in apps.StartupActionsManager or 
apps.startup.* )

I can't even figure out how actions that DO appear in the list are 
currently being added.  It's become a bit convoluted if you ask me.

Paul

**Comment by mattharris** [comment]
See linked PR in JMRI/JMRI#2472 for a solution to this.

**Comment by mattharris** [comment]
JMRI/JMRI#2472 now merged. Should be in latest 'nightly' and next JMRI release

**Comment by balazsracz** [comment]
Thanks!
